### PR TITLE
Add fastify-compression and fastify-cors

### PR DESCRIPTION
**Pull request by Sp3cker**
This change lets web apps call Formidable on behalf of the user (a browser `fetch` call). This change also adds `fastify-compression` which from my testing reduces response sizes by 2x-3x.

To test the cors change, I used this snippet in an app I'm working on:

```typescript
  const id = 147
  const detail = await fetch(`http://localhost:8080/ships/id?code=${id}`, {
      headers: { "content-type": "application/json" },
    }).then((r) => {
      if (r.ok) {
        return r.json();
      }
    });
    console.log(detail);
```

I tested the compression change by looking at the sizes on the Network tab of Chrome Devtools.

### CODE REVIEW

**Comment by Deivu** [comment]
Did you add something other than the fastify compression and cors in the recent commits?

**Comment by Sp3cker** [comment]
No. I forgot that pull requests work like that — sorry. I can get rid of those changes if you’d like. But they let you build this into a container, which is nice.

**Comment by Deivu** [comment]
You could include the docker support on an another branch then re-open a pr if you feel Formidable should have it built in. This pr should deal with fastify-compression and fastify-cors only for consistency

**Comment by Sp3cker** [comment]
Ok - I'll open a new PR with just the relevant changes. Please excuse my naiveté 🥴

**Pull request closed without merging**
